import { useEffect, useState } from "react";
import { Icon } from "@iconify/react";
import { apiUrl } from "../../../config/api";

export default function Vision() {
  const [data, setData] = useState(null);
  useEffect(() => { fetch(apiUrl("/api/faculty-vision")).then((r) => r.json()).then((d) => d.success && setData(d)); }, []);
  if (!data) return <section className="min-h-screen bg-[#faf8ef] pt-32"><p className="text-center text-gray-400">กำลังโหลดข้อมูล...</p></section>;
  const { vision, cards } = data;
  return <section className="min-h-screen bg-[#faf8ef] px-5 pb-16 pt-32"><div className="mx-auto max-w-6xl"><header className="mb-12 text-center"><span className="rounded-full bg-[#7A0019] px-4 py-1 text-xs font-bold text-white">FACULTY OF INDUSTRIAL TECHNOLOGY</span><h1 className="mt-4 text-3xl font-bold text-[#682122] sm:text-4xl">วิสัยทัศน์ พันธกิจ กลยุทธ์</h1><p className="mt-3 text-gray-500">แนวทางการพัฒนาคณะเทคโนโลยีอุตสาหกรรมอย่างยั่งยืน</p></header><div className="grid gap-6 lg:grid-cols-2"><article className="rounded-2xl border-t-4 border-[#682122] bg-white p-7 shadow-sm"><p className="text-xs font-bold text-[#7A0019]">PHILOSOPHY</p><h2 className="mt-2 text-2xl font-bold text-[#682122]">{vision.philosophy_title}</h2><p className="mt-3 leading-7 text-gray-600">{vision.philosophy_text}</p></article><article className="rounded-2xl border-t-4 border-[#682122] bg-white p-7 shadow-sm"><p className="text-xs font-bold text-[#7A0019]">AMBITION</p><h2 className="mt-2 text-2xl font-bold text-[#682122]">{vision.ambition_title}</h2><p className="mt-3 leading-7 text-gray-600">{vision.ambition_text}</p></article></div><div className="mt-12 text-center"><h2 className="text-2xl font-bold text-[#682122]">{vision.goal_title}</h2><p className="mt-2 text-gray-500">{vision.goal_subtitle}</p></div><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{cards.map((card) => <article key={card.id} className="rounded-2xl border-t-4 border-[#682122] bg-white p-6 shadow-sm"><Icon icon={card.icon} className="text-2xl text-[#7A0019]" /><h3 className="mt-4 font-bold text-[#682122]">{card.title}</h3><p className="mt-2 text-sm leading-6 text-gray-600">{card.description}</p></article>)}</div></div></section>;
}
