import { useEffect, useMemo, useRef, useState } from 'react';
import { apiUrl } from '../../config/api';

function MessageDialog({ title, messages, branches, onClose }) {
  const ref = useRef(null);
  useEffect(() => { const dialog = ref.current; dialog.showModal(); return () => dialog.close(); }, []);
  return <dialog ref={ref} onCancel={event => { event.preventDefault(); onClose(); }} className="m-auto max-h-[85vh] w-[calc(100%-2rem)] max-w-3xl rounded-2xl border border-slate-200 bg-white p-0 shadow-2xl backdrop:bg-slate-900/40"><div className="p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs text-slate-500">ข้อความจาก LINE</p><h2 className="mt-1 text-xl font-bold text-[#701D10]">{title}</h2><p className="mt-1 text-sm text-slate-500">{messages.length} ข้อความ</p></div><button type="button" onClick={onClose} className="rounded-lg border px-3 py-2 text-sm">ปิด</button></div><div className="mt-5 max-h-[55vh] divide-y overflow-y-auto">{messages.map(row => <article key={row.id} className="py-4"><p className="whitespace-pre-wrap break-words font-medium">{row.message}</p><p className="mt-2 text-xs text-slate-500">{branches[row.branch] || 'ยังไม่ระบุสาขา'} · {new Date(row.created_at).toLocaleString('th-TH')}</p></article>)}</div></div></dialog>;
}

export default function KnowledgeFaqDashboard() {
  const [data, setData] = useState(null), [error, setError] = useState(''), [selection, setSelection] = useState(null);
  useEffect(() => { const controller = new AbortController(); const timer = setTimeout(() => fetch(apiUrl('/api/admin/knowledge/messages'), { signal: controller.signal, headers: { Authorization: 'Bearer ' + localStorage.getItem('token') } }).then(async response => { const body = await response.json(); if (!response.ok || !body.success) throw new Error(body.message); setData(body); }).catch(value => { if (value.name !== 'AbortError') setError(value.message || 'โหลดคำถามที่พบบ่อยไม่สำเร็จ'); }), 0); return () => { clearTimeout(timer); controller.abort(); }; }, []);
  const groups = useMemo(() => {
    const source = data?.messages || []; const categories = new Map(); const questions = new Map();
    for (const row of source) { const category = categories.get(row.category) || []; category.push(row); categories.set(row.category, category); const item = questions.get(row.message) || { message: row.message, rows: [] }; item.rows.push(row); questions.set(row.message, item); }
    return { categories: [...categories.entries()].sort((a, b) => b[1].length - a[1].length), questions: [...questions.values()].sort((a, b) => b.rows.length - a.rows.length || b.rows[0].id - a.rows[0].id) };
  }, [data]);
  if (error) return <section className="rounded-2xl border bg-white p-5 text-sm text-red-700">{error}</section>;
  if (!data) return <section className="rounded-2xl border bg-white p-5 text-sm text-slate-500">กำลังโหลดคำถามที่พบบ่อยจาก LINE…</section>;
  const open = (title, messages) => setSelection({ title, messages });
  const pending = data.messages.filter(row => row.decision === 'review');
  return <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-bold text-[#701D10]">คำถามที่พบบ่อยจาก LINE</h2><p className="mt-1 text-sm text-slate-500">สรุปตามข้อความที่ N8N จัดประเภทแล้ว · กดดูรายละเอียดได้</p></div><span className="text-sm text-slate-500">{data.scope === 'all' ? 'ทุกสาขาและข้อมูลส่วนกลาง' : data.branches[data.scope]}</span></div>{data.legacy && <p className="mt-3 rounded-lg bg-amber-50 p-3 text-xs text-amber-900">กำลังแสดงคำถาม LINE ที่เคยบันทึกในระบบเดิม ข้อความใหม่จะแสดงจาก Workflow รุ่นปัจจุบันโดยอัตโนมัติ</p>}<div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{groups.categories.slice(0, 4).map(([name, messages]) => <button type="button" key={name} onClick={() => open(name, messages)} className="rounded-xl bg-[#701D10]/5 p-4 text-left transition hover:bg-[#701D10] hover:text-white focus-visible:outline focus-visible:outline-3 focus-visible:outline-[#c48759]"><p className="text-sm font-semibold">{name}</p><p className="mt-2 text-3xl font-bold">{messages.length}</p><p className="text-xs opacity-75">กดดูข้อความ</p></button>)}{!groups.categories.length && <p className="text-sm text-slate-500">ยังไม่มีข้อมูลคำถาม ระบบจะแสดงข้อความใหม่หลัง N8N ส่งผลการจัดประเภท</p>}</div><div className="mt-6 grid gap-6 lg:grid-cols-2"><div><h3 className="font-bold">ข้อความที่พบบ่อย</h3>{groups.questions.length ? <ol className="mt-2 divide-y text-sm">{groups.questions.slice(0, 5).map((item, index) => <li key={item.message}><button type="button" onClick={() => open(item.message, item.rows)} className="flex w-full gap-3 py-3 text-left hover:text-[#701D10]"><span className="font-bold">{index + 1}</span><span className="flex-1 break-words">{item.message}</span><span className="text-xs text-slate-500">{item.rows.length} ครั้ง</span></button></li>)}</ol> : <p className="mt-2 text-sm text-slate-500">ยังไม่มีข้อมูลคำถาม</p>}</div><div><h3 className="font-bold">คำถามที่ควรเพิ่มข้อมูล</h3>{pending.length ? <button type="button" onClick={() => open('คำถามที่ควรเพิ่มข้อมูล', pending)} className="mt-2 text-left text-sm text-[#701D10] underline">มี {pending.length} ข้อความที่ AI ยังตอบจากข้อมูลไม่ได้ — กดดู</button> : <p className="mt-2 text-sm text-slate-500">ยังไม่มีคำถามที่รอเพิ่มข้อมูล</p>}</div></div>{selection && <MessageDialog title={selection.title} messages={selection.messages} branches={data.branches} onClose={() => setSelection(null)} />}</section>;
}
