import { useEffect, useState } from 'react';
import { apiUrl } from '../../config/api';

export default function KnowledgeFaqDashboard() {
  const [data, setData] = useState(null), [error, setError] = useState('');
  useEffect(() => { const controller = new AbortController(); const timer = setTimeout(() => fetch(apiUrl('/api/admin/knowledge'), { signal: controller.signal, headers: { Authorization: 'Bearer ' + localStorage.getItem('token') } }).then(async response => { const body = await response.json(); if (!response.ok || !body.success) throw new Error(); setData(body); }).catch(value => { if (value.name !== 'AbortError') setError('โหลดคำถามที่พบบ่อยไม่สำเร็จ'); }), 0); return () => { clearTimeout(timer); controller.abort(); }; }, []);
  if (error) return <section className="rounded-2xl border bg-white p-5 text-sm text-red-700">{error}</section>;
  if (!data) return <section className="rounded-2xl border bg-white p-5 text-sm text-slate-500">กำลังโหลดคำถามที่พบบ่อย…</section>;
  const categories = [...data.questions, ...data.answers].reduce((map, row) => map.set(row.category, (map.get(row.category) || 0) + (row.occurrences || 1)), new Map());
  const questions = [...data.questions].sort((a, b) => (b.occurrences || 0) - (a.occurrences || 0)).slice(0, 5);
  return <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-bold text-[#701D10]">คำถามที่พบบ่อยจาก LINE</h2><p className="mt-1 text-sm text-slate-500">สรุปตามข้อมูลในขอบเขตที่บัญชีนี้เข้าถึงได้</p></div><span className="text-sm text-slate-500">{data.scope === 'all' ? 'ทุกสาขาและข้อมูลส่วนกลาง' : data.branches[data.scope]}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[...categories.entries()].sort((a, b) => b[1] - a[1]).slice(0, 4).map(([name, count]) => <div key={name} className="rounded-xl bg-[#701D10]/5 p-4"><p className="text-sm font-semibold">{name}</p><p className="mt-2 text-2xl font-bold text-[#701D10]">{count}</p><p className="text-xs text-slate-500">คำถาม / ข้อมูลที่บันทึก</p></div>)}{!categories.size && <p className="text-sm text-slate-500">ยังไม่มีข้อมูลคำถาม</p>}</div><div className="mt-5"><h3 className="text-sm font-bold">คำถามที่ยังควรเพิ่มข้อมูล</h3>{questions.length ? <ol className="mt-2 divide-y text-sm">{questions.map((row, index) => <li key={row.id} className="flex gap-3 py-3"><span className="font-bold text-[#701D10]">{index + 1}</span><span className="flex-1">{row.question}</span><span className="text-xs text-slate-500">{row.occurrences || 1} ครั้ง</span></li>)}</ol> : <p className="mt-2 text-sm text-slate-500">ยังไม่มีคำถามที่รอเพิ่มข้อมูล</p>}</div></section>;
}
